-- Decathlon csendes nyitvatartás – 24 áruház feltöltése
-- Futtatás: Supabase Dashboard → SQL Editor → New Query → Run

INSERT INTO public.places (
  slug, name, category, city, postal_code, address,
  phone, website, description, why_friendly,
  status, latitude, longitude
) VALUES
('decathlon-budaors',
 'Decathlon Budaörs',
 'bolt-bevasarlohely', 'Budaörs', '2040', 'Baross utca 146.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Budaörsön, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.4489, 18.9584),

('decathlon-budapest-futo',
 'Decathlon Budapest – Futó utca',
 'bolt-bevasarlohely', 'Budapest', '1083', 'Futó u. 37.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Budapest VIII. kerületében, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.4889, 19.0792),

('decathlon-budapest-nyugati',
 'Decathlon Budapest – Nyugati tér',
 'bolt-bevasarlohely', 'Budapest', '1066', 'Nyugati tér 1-2.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Budapest VI. kerületében, a Nyugati pályaudvar közelében, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.5073, 19.0565),

('decathlon-budapest-soroksari',
 'Decathlon Budapest – Soroksár',
 'bolt-bevasarlohely', 'Budapest', '1239', 'Bevásárló u. 2.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Budapest XXIII. kerületében (Soroksár), ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.3995, 19.0935),

('decathlon-csomor',
 'Decathlon Csömör',
 'bolt-bevasarlohely', 'Csömör', '2141', 'Határ út 2.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Csömörön, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.5523, 19.2345),

('decathlon-dunakeszi',
 'Decathlon Dunakeszi',
 'bolt-bevasarlohely', 'Dunakeszi', '2120', 'Pallag utca 3.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Dunakeszin, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.6198, 19.1297),

('decathlon-maglod',
 'Decathlon Maglód',
 'bolt-bevasarlohely', 'Maglód', '2234', 'Kállai Pál utca 2.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Maglódon, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.4488, 19.3524),

('decathlon-bekescsaba',
 'Decathlon Békéscsaba',
 'bolt-bevasarlohely', 'Békéscsaba', '5600', 'Szarvasi út 68/2.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Békéscsabán, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.6795, 21.0834),

('decathlon-debrecen',
 'Decathlon Debrecen',
 'bolt-bevasarlohely', 'Debrecen', '4002', 'Balmazújvárosi út 11.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Debrecenben, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.5218, 21.6295),

('decathlon-dunaujvaros',
 'Decathlon Dunaújváros',
 'bolt-bevasarlohely', 'Dunaújváros', '2400', 'Kandó Kálmán tér 12.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Dunaújvárosban, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.9789, 18.9316),

('decathlon-eger',
 'Decathlon Eger',
 'bolt-bevasarlohely', 'Eger', '3300', 'II. Rákóczi Ferenc út 100.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Egerben, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.8954, 20.3732),

('decathlon-gyor',
 'Decathlon Győr',
 'bolt-bevasarlohely', 'Győr', '9012', 'Királyszék út 31.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Győrben, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.6875, 17.6504),

('decathlon-kecskemet',
 'Decathlon Kecskemét',
 'bolt-bevasarlohely', 'Kecskemét', '6000', 'Dunaföldvári út 2/b.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Kecskeméten, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.8975, 19.6912),

('decathlon-miskolc',
 'Decathlon Miskolc',
 'bolt-bevasarlohely', 'Miskolc', '3527', 'József Attila út 83.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Miskolcon, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 48.0985, 20.7863),

('decathlon-nyiregyhaza',
 'Decathlon Nyíregyháza',
 'bolt-bevasarlohely', 'Nyíregyháza', '4400', 'Pazonyi út 36.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Nyíregyházán, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.9554, 21.7169),

('decathlon-pecs',
 'Decathlon Pécs',
 'bolt-bevasarlohely', 'Pécs', '7634', 'Makay I. u. 7.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Pécsen, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.0816, 18.2350),

('decathlon-sopron',
 'Decathlon Sopron',
 'bolt-bevasarlohely', 'Sopron', '9400', 'Ipar körút 31.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Sopronban, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.6795, 16.5898),

('decathlon-szeged',
 'Decathlon Szeged',
 'bolt-bevasarlohely', 'Szeged', '6728', 'Zápor út 4.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Szegeden, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.2458, 20.1415),

('decathlon-szekesfehervar',
 'Decathlon Székesfehérvár',
 'bolt-bevasarlohely', 'Székesfehérvár', '8000', 'Holland fasor 3.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Székesfehérváron, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.1887, 18.4273),

('decathlon-szolnok',
 'Decathlon Szolnok',
 'bolt-bevasarlohely', 'Szolnok', '5000', 'Felső Szandai Rét 1.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Szolnokon, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.1898, 20.2015),

('decathlon-szombathely',
 'Decathlon Szombathely',
 'bolt-bevasarlohely', 'Szombathely', '9700', 'Bálványkő út 3.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Szombathelyen, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.2254, 16.6173),

('decathlon-vertesszolos',
 'Decathlon Vértesszőlős',
 'bolt-bevasarlohely', 'Vértesszőlős', '2837', 'Határ út 1-3.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Vértesszőlősön (Tatabánya közelében), ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.5954, 18.3254),

('decathlon-veszprem',
 'Decathlon Veszprém',
 'bolt-bevasarlohely', 'Veszprém', '8200', 'Külső-Kádártai út 3.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Veszprémben, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 47.0845, 17.9127),

('decathlon-zalaegerszeg',
 'Decathlon Zalaegerszeg',
 'bolt-bevasarlohely', 'Zalaegerszeg', '8900', 'Balatoni út 5.',
 NULL, 'https://www.decathlon.hu/c/lp/csendes-nyitvatartas-decathlon_c66668bd-b433-4bdb-a924-d12b49ff24a0',
 'Decathlon sporteszköz-áruház Zalaegerszegen, ahol elérhető a csendes nyitvatartás program.',
 'Csendes nyitvatartás: hétfőn és csütörtökön 10:00–12:00 között az áruház zene nélkül üzemel, csökkentett világítással. A hangosbemondót kizárólag biztonsági esetekben használják a nyugodtabb légkör érdekében.',
 'approved', 46.8412, 16.8405)

ON CONFLICT (slug) DO NOTHING;
