-- Kölyökpark helyszínek (8 db, Szeged bezárt kihagyva)
-- Supabase SQL Editor → New query → Paste → Run

INSERT INTO public.places (slug, name, category, city, postal_code, address, phone, website, description, why_friendly, status)
VALUES
  ('kolyokpark-arkad', 'Kölyökpark Árkád', 'jatszohaz', 'Budapest', '1106', '1106 Budapest, Örs vezér tere 25/A', '06-70/391-1484', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved'),
  ('kolyokpark-mammut', 'Kölyökpark Mammut', 'jatszohaz', 'Budapest', '1024', '1024 Budapest, Lövőház u. 1–5.', '06-70/391-1482', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved'),
  ('kolyokpark-polus', 'Kölyökpark Pólus', 'jatszohaz', 'Budapest', '1152', '1152 Budapest, Szentmihályi út 131.', '06-70/391-1483', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved'),
  ('kolyokpark-sarkany-center', 'Kölyökpark Sárkány Center', 'jatszohaz', 'Budapest', '1183', '1183 Budapest, Gyömrői út 79–83.', '06-70/418-5042', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Speciális igényű gyermekekkel is szívesen foglalkoznak. A pontos kedvezményekről érdeklődjön a helyszínen.', 'approved'),
  ('kolyokpark-etele-plaza', 'Kölyökpark Etele Pláza', 'jatszohaz', 'Budapest', '1119', '1119 Budapest, Hadak útja 1.', '06-70/558-6658', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeket nevelő intézményből érkező csoportoknak hétköznap délelőtt 1 óra játékot biztosítanak térítésmentesen, előzetes telefonos bejelentkezéssel.', 'approved'),
  ('kolyokpark-kecskemet', 'Kölyökpark Kecskemét', 'jatszohaz', 'Kecskemét', '6000', '6000 Kecskemét, Korona u. 2.', '06-76/321-115', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved'),
  ('kolyokpark-nagykanizsa', 'Kölyökpark Nagykanizsa', 'jatszohaz', 'Nagykanizsa', '8800', '8800 Nagykanizsa, Táborhely út 4.', '06-93/318-215', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved'),
  ('kolyokpark-veszprem', 'Kölyökpark Veszprém', 'jatszohaz', 'Veszprém', '8200', '8200 Veszprém, Külső-Kádártai u. 3.', '06-70/622-7085', 'https://kolyokpark.hu', 'KÖLYÖKPARK a Tudatos Játszóház!
Mert számunkra fontos, milyen játékokat kínálunk a gyerekeknek!

A KÖLYÖKPARK játékrendszerét mozgásterapeuták, pszichológusok és korai fejlesztő szakemberek javaslatai alapján állítottuk össze. Nálunk speciális mozgás- és képességfejlesztő játékrendszerben mozoghatnak a gyerekek. A szabad, örömteli játék játszva fejleszt, okosít! Bébi játszó és Baba-Mama szoba ingyenes pelenkázási és szoptatási lehetőséggel. Szakképzett felügyelet felár nélkül 4 éves kortól. Társadalmi felelősségvállalás, esztétikai nevelés, környezettudatosságra nevelés, állandó megújulás.', 'Mentálisan sérült és/vagy mozgásban korlátozott gyermekeknek csak fél órát kell fizetni és 2 órát maradhatnak szülői felügyelettel. Hatósági igazolvány felmutatása szükséges.', 'approved')
ON CONFLICT (slug) DO NOTHING;
