-- SNI Iránytű — kezdő adatfeltöltés (3. fázis)
-- Futtatás a schema.sql UTÁN, Supabase SQL Editorban.

insert into public.categories (slug, name, icon, sort_order) values
  ('etterem', 'Étterem', '🍽️', 0),
  ('cukraszda-kavezo', 'Cukrászda / kávézó', '☕', 1),
  ('jatszoter', 'Játszótér', '🛝', 2),
  ('jatszohaz', 'Játszóház', '🧸', 3),
  ('fodrasz', 'Fodrász', '✂️', 4),
  ('fogorvos', 'Fogorvos', '🦷', 5),
  ('orvos', 'Orvos', '🩺', 6),
  ('fejlesztohaz', 'Fejlesztőház', '🧩', 7),
  ('gyogypedagogus-terapia', 'Gyógypedagógus / terápia', '🧠', 8),
  ('lovarda-allatasszisztalt-program', 'Lovarda / állatasszisztált program', '🐴', 9),
  ('mozi-szinhaz', 'Mozi / színház', '🎬', 10),
  ('muzeum-kiallitas', 'Múzeum / kiállítás', '🏛️', 11),
  ('szallashely', 'Szálláshely', '🛏️', 12),
  ('kirandulohely', 'Kirándulóhely', '🌳', 13),
  ('bolt-bevasarlohely', 'Bolt / bevásárlóhely', '🛍️', 14),
  ('egyeb', 'Egyéb', '📍', 15)
on conflict (slug) do update set name = excluded.name, icon = excluded.icon, sort_order = excluded.sort_order;

insert into public.places (slug, name, category, city, postal_code, address, phone, website, description, why_friendly, status) values
('mesemuzeum', 'Mesemúzeum', 'muzeum-kiallitas', 'Budapest', '1013', '1013 Budapest, Döbrentei utca 15.', '+36 1 202 4020', 'https://mesemuzeum.hu/hu/autizmusbarat-mesemuzeum', 'Gyerekmúzeum és irodalmi-mesés kiállítótér.', 'Autizmusbarát terek, piktogramok, pihenősarok, szociális történet, vezetőfüzet.', 'approved'),
('modem-modern-es-kortars-muveszeti-kozpont', 'MODEM Modern és Kortárs Művészeti Központ', 'muzeum-kiallitas', 'Debrecen', '4026', '4026 Debrecen, Baltazár Dezső tér 1.', null, 'https://modemart.hu/autizmusbarat-muzeum/', 'Kortárs művészeti központ.', 'Csendesebb idősáv, fény- és hangadaptáció, piktogramok, AAK/PECS/GoTalk támogatás.', 'approved'),
('magyar-mezogazdasagi-muzeum-es-konyvtar', 'Magyar Mezőgazdasági Múzeum és Könyvtár', 'muzeum-kiallitas', 'Budapest', '1146', '1146 Budapest, Vajdahunyadvár, Városliget', '+36 1 422 0765', 'https://www.mezogazdasagimuzeum.hu/tanulas/foglalkozasok-sajatos-nevelesi-igenyueknek/gyere-kozelebb-autizmusbarat-muzeum', 'Mezőgazdasági és természeti témájú múzeum.', '„Gyere közelebb” autizmusbarát múzeumi foglalkozások és csendes óra.', 'approved'),
('magyar-penzmuzeum-es-latogatokozpont', 'Magyar Pénzmúzeum és Látogatóközpont', 'muzeum-kiallitas', 'Budapest', '1122', '1122 Budapest, Krisztina körút 6.', null, 'https://www.penzmuzeum.hu', 'Interaktív pénzügyi kiállítás.', 'AOSZ-szal együttműködve könnyebben befogadható, autizmusbarátabb kiállítási élmény.', 'approved'),
('magyar-vasuttorteneti-park', 'Magyar Vasúttörténeti Park', 'muzeum-kiallitas', 'Budapest', '1142', '1142 Budapest, Tatai út 95.', null, 'https://vasuttortenetipark.hu/rendezvenyek/autizmusbarat-program-a-vasuttorteneti-parkban-2/', 'Vasúti skanzen és családi programhelyszín.', 'Cseperedő Alapítvánnyal szervezett autizmusbarát program.', 'approved'),
('budapesti-fesztivalzenekar-bfz-proba-ter', 'Budapesti Fesztiválzenekar – BFZ Próba/Tér', 'mozi-szinhaz', 'Budapest', '1033', '1033 Budapest, Selmeci utca 14–16.', null, 'https://www.bfz.hu', 'Koncerthelyszín és zenei programok.', 'Autizmusbarát Kakaókoncerteket szerveztek Cseperedő támogatással.', 'approved'),
('apollo-mozi-debrecen', 'Apolló Mozi Debrecen', 'mozi-szinhaz', 'Debrecen', '4025', '4025 Debrecen, Miklós utca 1.', null, 'https://apollo-mozi.hu', 'Art mozi Debrecenben.', 'Autizmusbarát csendes vetítések: kisebb hangerő, tompított világítás, felkészített személyzet.', 'approved'),
('fovarosi-nagycirkusz', 'Fővárosi Nagycirkusz', 'mozi-szinhaz', 'Budapest', '1146', '1146 Budapest, Állatkerti körút 12/a', null, 'https://fnc.hu/autizmus-barat-kulturalis-transzformaciok/', 'Állandó cirkuszi játszóhely.', 'Cseperedővel közösen akadálymentes, autizmusbarát előadást alakított ki.', 'approved'),
('veszpremi-petofi-szinhaz', 'Veszprémi Petőfi Színház', 'mozi-szinhaz', 'Veszprém', '8200', '8200 Veszprém, Óvári Ferenc utca 2.', null, 'https://www.petofiszinhaz.hu', 'Veszprémi kőszínház.', 'AOSZ-kártya partner, kedvezményes jegyár autizmust igazoló kártyával.', 'approved'),
('csodak-palotaja', 'Csodák Palotája', 'muzeum-kiallitas', 'Budapest', '1036', '1036 Budapest, Bécsi út 38–44.', null, 'https://www.csopa.hu', 'Interaktív tudományos élményközpont.', 'AOSZ-kártya partner; jelképes/kedvezményes belépés.', 'approved'),
('godolloi-kiralyi-kastely', 'Gödöllői Királyi Kastély', 'muzeum-kiallitas', 'Gödöllő', '2100', '2100 Gödöllő, Grassalkovich-kastély 5852', null, 'https://www.kiralyikastely.hu', 'Barokk kastélymúzeum.', 'AOSZ-kártya partner; kedvezmény/ingyenes állandó kiállítási belépés AOSZ-kártyával.', 'approved'),
('tisza-tavi-okocentrum', 'Tisza-tavi Ökocentrum', 'kirandulohely', 'Poroszló', '3388', '3388 Poroszló, Kossuth Lajos út 41.', null, 'https://tiszataviokocentrum.hu', 'Természetismereti látogatóközpont, akvárium és kilátó.', 'AOSZ-kártya partner; kedvezményes jegyár.', 'approved'),
('fovarosi-allat-es-novenykert', 'Fővárosi Állat- és Növénykert', 'kirandulohely', 'Budapest', '1146', '1146 Budapest, Állatkerti körút 6–12.', null, 'https://zoobudapest.com', 'Nagy állatkert a Városligetben.', 'AOSZ-kártya partner; kedvezményes partneri jegy.', 'approved'),
('veszpremi-allatkert', 'Veszprémi Állatkert', 'kirandulohely', 'Veszprém', '8200', '8200 Veszprém, Kittenberger Kálmán utca 17.', null, 'https://www.veszpzoo.hu', 'Vadaspark és családi kirándulóhely.', 'AOSZ-kártya partner; kedvezményes partneri jegy.', 'approved'),
('kecskemeti-vadaskert', 'Kecskeméti Vadaskert', 'kirandulohely', 'Kecskemét', '6000', '6000 Kecskemét, Műkert 1.', null, 'https://www.zookecskemet.hu', 'Kisebb, családias vadaskert.', 'AOSZ-kártya partner; kedvezményes jegyár.', 'approved'),
('tropicarium-es-oceanarium-budapest', 'Tropicarium és Oceanárium Budapest', 'kirandulohely', 'Budapest', '1222', '1222 Budapest, Nagytétényi út 37–43.', null, 'https://tropicarium.hu', 'Beltéri akvárium és állatbemutató.', 'AOSZ-kártya partner; kedvezményes jegyár.', 'approved');

insert into public.places (slug, name, category, city, postal_code, address, phone, website, description, why_friendly, status) values
('erdei-kucko-jatszohaz', 'Erdei Kuckó Játszóház', 'jatszohaz', 'Budapest', '1141', '1141 Budapest, Egressy út 113. J–K', null, 'https://erdeikucko.hu', 'Beltéri játszóház.', 'AOSZ-kártya partner; kedvezményes belépő AOSZ-kártyával.', 'approved'),
('pindur-pandur-jatszohaz', 'Pindúr Pandúr Játszóház', 'jatszohaz', 'Budapest', null, 'Budapest – pontos cím ellenőrizendő', null, null, 'Beltéri játszóház.', 'AOSZ-kártya partner; kedvezményes jegyár.', 'approved'),
('minipolisz', 'MiniPolisz', 'jatszohaz', 'Budapest', '1065', '1065 Budapest, Király utca 8–10.', null, 'https://www.minipolisz.hu', 'Interaktív városi szerepjáték-játszóház.', 'AOSZ-kártya partner; megállapodás szerinti kedvezmény.', 'approved'),
('kolyok-obol-jatszohaz', 'Kölyök-öböl Játszóház', 'jatszohaz', 'Budapest', '1117', '1117 Budapest, Hengermalom út 19–21.', null, 'https://www.kolyokobol.hu', 'Játszóház és gyerekprogram-helyszín.', 'AOSZ-kártya partner; megállapodás szerinti kedvezmény.', 'approved'),
('benczur-kert-jatszoter', 'Benczúr kert játszótér', 'jatszoter', 'Budapest', '1068', '1068 Budapest, Benczúr köz 9.', null, null, 'Kisebb városi játszótér meseelemekkel.', 'Auti.hu nyári ajánlóban szerepel autista gyerekkel tervezhető helyszínként.', 'approved'),
('katica-tanya-elmenykozpont', 'Katica Tanya Élményközpont', 'kirandulohely', 'Patca', '7477', '7477 Patca, Fő utca 65.', null, 'https://katicatanya.hu', 'Élményközpont, farm és családi programhely.', 'AOSZ-kártya partner; 10% kedvezmény.', 'approved'),
('balatonibob-szabadidopark', 'BalatoniBob Szabadidőpark', 'kirandulohely', 'Balatonfűzfő', '8220', '8220 Balatonfűzfő, Uszoda utca 2.', null, 'https://balatonibob.hu', 'Bobpálya és családi szabadidőpark.', 'AOSZ-kártya partner; kedvezményes ár.', 'approved'),
('leanyfalui-termalfurdo', 'Leányfalui Termálfürdő', 'egyeb', 'Leányfalu', '2016', '2016 Leányfalu, Móricz Zsigmond út 142.', null, 'https://leanyfurdo.hu', 'Termálfürdő.', 'AOSZ-kártya partner; kedvezményes jegyár.', 'approved'),
('harkanyi-gyogyfurdo', 'Harkányi Gyógyfürdő', 'egyeb', 'Harkány', '7815', '7815 Harkány, Kossuth Lajos utca 7.', null, 'https://harkanyfurdo.hu', 'Gyógy- és strandfürdő.', 'AOSZ-kártya partner; 10% kedvezmény.', 'approved'),
('hagymatikum-gyogyfurdo', 'Hagymatikum Gyógyfürdő', 'egyeb', 'Makó', '6900', '6900 Makó, Makovecz tér 6.', null, 'https://hagymatikum.hu', 'Gyógyfürdő és élményfürdő.', 'AOSZ-kártya partner; 30% kedvezmény napijegyből.', 'approved'),
('sobuda-kristalyso-barlang', 'Sóbuda Kristálysó Barlang', 'egyeb', 'Budapest', '1036', '1036 Budapest, Lajos utca 74–76.', null, 'https://sobuda.hu', 'Sóbarlang, relaxációs és egészségmegőrző hely.', 'AOSZ-kártya partner; 15% kedvezmény.', 'approved'),
('code-zero', 'Code Zero', 'etterem', 'Budapest', '1056', '1056 Budapest, Papnövelde utca 10.', null, 'https://www.facebook.com/codezerobudapest', 'Vendéglátóhely.', 'Résztvevő az AOSZ AutSense éttermi szemléletformáló programjában.', 'approved'),
('galopp-major-csarda', 'Galopp Major Csárda', 'etterem', 'Gyál', '2360', '2360 Gyál, Galopp Major', null, 'https://www.galoppmajor.hu', 'Csárda és rendezvényhelyszín.', 'AutSense résztvevő; a forrás szerint akadálymentes rendelés és személyzeti érzékenyítés is motiváció volt.', 'approved'),
('hatpottyos-etterem', 'Hatpöttyös Étterem', 'etterem', 'Székesfehérvár', '8000', '8000 Székesfehérvár, Szent István tér 9.', null, 'https://www.hatpottyos.hu', 'Társadalmi küldetésű étterem.', 'AutSense résztvevő; sérült/megváltozott munkaképességű emberek integrációjára épülő szemlélet.', 'approved'),
('batyu-teka-tobb-mint-etterem', 'Batyu-Téka, több mint Étterem', 'etterem', 'Miskolc', '3530', '3530 Miskolc, Arany János utca 4.', null, 'http://batyuteka.hu/', 'Közösségi és szociális funkciójú étterem.', 'AutSense résztvevő; a forrás szerint autizmussal és fogyatékossággal élő emberek is dolgoznak itt, fejlesztő-játszóház kapcsolódott hozzá.', 'approved'),
('nem-adom-fel-cafe-es-bar', 'Nem Adom Fel Café és Bár', 'cukraszda-kavezo', 'Budapest', '1082', '1082 Budapest, Baross utca 86.', null, 'http://nemadomfelkavezo.hu/', 'Inkluzív kávézó és közösségi hely.', 'AutSense résztvevő; fogyatékossággal élő, köztük autista munkavállalók foglalkoztatásához kapcsolódik.', 'approved');

insert into public.places (slug, name, category, city, postal_code, address, phone, website, description, why_friendly, status) values
('egyenlo-kavezo', 'Egyenlő Kávézó', 'cukraszda-kavezo', 'Budapest', null, 'Budapest VIII. kerület – pontos cím ellenőrizendő', '+36 30 592 9074', 'https://egyenlocafe.hu/', 'Kávézó, rendezvényhelyszín, gyermeksarokkal.', 'Védett munkahely értelmi fogyatékos és autista kollégáknak; befogadó szemléletű hely.', 'approved'),
('kockacsoki-kockapont-kozossegi-kavezo', 'KockaCsoki – KockaPont Közösségi Kávézó', 'cukraszda-kavezo', 'Budapest', '1134', '1134 Budapest, Dózsa György út 32.', null, 'https://www.kockacsoki.com', 'Csokoládémanufaktúra és közösségi kávézó.', 'Autista fiatalokat foglalkoztató, autizmusbarát közösségi térként ismert.', 'approved'),
('barathegyi-panzio-barathegyi-majorsag', 'Baráthegyi Panzió / Baráthegyi Majorság', 'szallashely', 'Miskolc', '3528', '3528 Miskolc, Majorság utca 7.', '+36 30 681 4482', 'https://www.barathegyrelax.hu', 'Panzió és élményhelyszín a Szimbiózis Alapítvány környezetében.', 'Fogyatékossággal élő és autista embereket támogató szociális farm/közeg.', 'approved'),
('autista-mintahaz-heim-pal-adtc', 'Autista Mintaház – Heim Pál ADTC', 'orvos', 'Budapest', '1131', '1131 Budapest, Gyermek tér 2.', '+36 1 340 8754; +36 30 425 3765', 'https://autistamintahaz.hu', 'Diagnosztikai és terápiás centrum.', 'Kifejezetten autizmus spektrumzavarral élő gyermekek és családjaik támogatására jött létre; vizuális, strukturált támogatás.', 'approved'),
('nemzetkozi-cseperedo-alapitvany', 'Nemzetközi Cseperedő Alapítvány', 'fejlesztohaz', 'Budapest', '1137', '1137 Budapest, Radnóti Miklós utca 9. I. emelet', '+36 70 646 2746', 'https://cseperedo.hu', 'Autizmus diagnosztika, fejlesztés, szakmai programok.', 'Autizmusbarát kulturális protokollokat és vizuális segédanyagokat fejleszt; autizmus-specifikus szakmai központ.', 'approved'),
('mosoly-fejlesztohaz', 'Mosoly Fejlesztőház', 'fejlesztohaz', 'Budapest', '1135', '1135 Budapest, Jász utca 99.', '+36 70 850 9070', 'https://mosolyhaz.hu', 'Gyermekfejlesztő központ.', 'Szolgáltatásai között autizmus-specifikus fejlesztés is szerepel.', 'approved'),
('mano-fejleszto-es-terapias-kozpont', 'Manó Fejlesztő- és Terápiás Központ', 'fejlesztohaz', 'Budapest', '1114', '1114 Budapest, Vásárhelyi Pál utca 8. fszt. 2.', '+36 30 525 8014', 'https://www.manofejleszto.hu/autizmus-specifikus-fejlesztes/', 'Fejlesztő- és terápiás központ.', 'Autizmus-specifikus fejlesztést és szociális-kommunikációs fejlesztést hirdet.', 'approved'),
('kis-lepesek-alapitvany-aba-terapias-kozpont', 'Kis Lépések Alapítvány – ABA Terápiás Központ', 'gyogypedagogus-terapia', 'Budapest', '1124', '1124 Budapest, Stromfeld Aurél út 8.', null, 'https://kislepesek.hu', 'ABA-alapú terápiás és szakmai központ.', 'Autizmusban érintett gyermekek fejlesztésére fókuszáló ABA terápiás központ.', 'approved'),
('checkpoint-rendelo', 'Checkpoint Rendelő', 'orvos', 'Budapest', null, 'Budapest – pontos cím ellenőrizendő', null, 'https://checkpointrendelo.hu', 'Gyermekpszichiátriai/fejlesztő szolgáltatások.', 'Saját leírása szerint autizmusbarát megközelítés, kis létszámú foglalkozások, személyre szabott fejlesztés.', 'approved'),
('hungarodental-junior-smile-teeth-rendelo', 'HungaroDental Junior / Smile & Teeth rendelő', 'fogorvos', 'Budapest', '1026', '1026 Budapest, Pasaréti út 57.', '+36 70 772 1315', 'https://www.hungarodental.hu/specialis-nevelesi-igenyu-gyermekek-beintegralasa-a-fogaszati-ellatas-vilagaba/', 'Gyermekfogászat és fogászati ellátás.', 'Nyugodt, kevés ingerű autizmusbarát környezet, vizuális segédeszközök, rugalmas kommunikáció.', 'approved'),
('semmelweis-egyetem-fok-arc-allcsont-szajsebeszeti-es-fogaszati-klinika', 'Semmelweis Egyetem FOK – Arc-, Állcsont-, Szájsebészeti és Fogászati Klinika', 'fogorvos', 'Budapest', '1085', '1085 Budapest, Mária utca 52.', '+36 1 266 0457', 'https://semmelweis.hu/szajsebeszet/elerhetoseg/', 'Egyetemi fogászati és szájsebészeti klinika.', 'Fogyatékkal élők fogászati centrumaként szerepel autizmus-információs forrásokban.', 'approved'),
('keviczky-ferenc-fodrasz', 'Keviczky Ferenc fodrász', 'fodrasz', 'Hatvan', null, 'Hatvan – pontos cím nem publikus', null, 'https://marsalapitvany.hu/mars-csillagok/keviczky-ferenc/', 'Gyermekekkel türelmes fodrászként ajánlott szakember.', 'Szülői ajánlás szerint előre jelzi a lépéseket, autizmusbarát módon bánik gyerekekkel.', 'approved'),
('toldi-haz-alsotold', 'Toldi Ház Alsótold', 'szallashely', 'Alsótold', '3069', '3069 Alsótold, Szabadság utca 1–3.', null, 'https://hovamenjek.hu/alsotold/szallas', 'Családbarát szállás a Cserhátban.', 'Forrás szerint kiemelt figyelmet kapnak az autista és SNI gyerekek.', 'approved'),
('kapcsolat-lovasterapia-kozpont', 'KAPCSOLAT Lovasterápia Központ', 'lovarda-allatasszisztalt-program', 'Budapest környéke', null, 'Budapest környéke – pontos helyszín egyeztetéssel', '+36 30 554 3774', 'https://www.lovasterapia.com/hu/kapcsolat-lovasterapia-kozpont/terapia/gyermek/', 'Gyermekeknek szóló lóasszisztált terápia.', 'Saját leírásuk szerint autisztikus gyerekekkel és fiatalokkal is dolgoznak lóasszisztált terápiával.', 'approved'),
('kutyaval-egy-mosolyert-alapitvany', 'Kutyával Egy Mosolyért Alapítvány', 'lovarda-allatasszisztalt-program', 'Kecskemét', '6000', '6000 Kecskemét – pontos helyszín egyeztetéssel', null, 'https://kutyavalegymosolyert.hu/alapitvany/segito-kutyak/', 'Segítőkutya- és terápiás kutyás programok.', 'Autista segítő kutyákat is képez; források szerint autista gyermekek kutyás terápiájában is részt vett.', 'approved');
