// Magyarország vármegyéi és települései
// Tartalmazza az összes várost és a fontosabb nagyközségeket.
// Az "– Egyéb –" opciónál szabad szöveges megadás lehetséges.

export const MEGYEK: string[] = [
  "Budapest",
  "Baranya",
  "Bács-Kiskun",
  "Békés",
  "Borsod-Abaúj-Zemplén",
  "Csongrád-Csanád",
  "Fejér",
  "Győr-Moson-Sopron",
  "Hajdú-Bihar",
  "Heves",
  "Jász-Nagykun-Szolnok",
  "Komárom-Esztergom",
  "Nógrád",
  "Pest",
  "Somogy",
  "Szabolcs-Szatmár-Bereg",
  "Tolna",
  "Vas",
  "Veszprém",
  "Zala",
];

export const EGYEB_OPCIO = "– Egyéb (szabad megadás) –";

export const TELEPULESEK: Record<string, string[]> = {
  "Budapest": [
    "Budapest",
    "Budapest I. kerület",
    "Budapest II. kerület",
    "Budapest III. kerület",
    "Budapest IV. kerület",
    "Budapest V. kerület",
    "Budapest VI. kerület",
    "Budapest VII. kerület",
    "Budapest VIII. kerület",
    "Budapest IX. kerület",
    "Budapest X. kerület",
    "Budapest XI. kerület",
    "Budapest XII. kerület",
    "Budapest XIII. kerület",
    "Budapest XIV. kerület",
    "Budapest XV. kerület",
    "Budapest XVI. kerület",
    "Budapest XVII. kerület",
    "Budapest XVIII. kerület",
    "Budapest XIX. kerület",
    "Budapest XX. kerület",
    "Budapest XXI. kerület",
    "Budapest XXII. kerület",
    "Budapest XXIII. kerület",
    EGYEB_OPCIO,
  ],
  "Baranya": [
    "Pécs", "Komló", "Mohács", "Siklós", "Szigetvár", "Pécsvárad", "Sellye", "Szentlőrinc",
    "Abaliget", "Beremend", "Birján", "Bogád", "Bóly", "Bosta", "Cserkút", "Drávaszabolcs",
    "Drávapalkonya", "Drávapiski", "Dunaszekcső", "Egyházasharaszti", "Ellend", "Erdősmecske",
    "Garé", "Gerde", "Gerényes", "Görcsöny", "Gyód", "Gyöngyösmellék", "Harkány",
    "Hegyszentmárton", "Hosszúhetény", "Ibafa", "Keszü", "Kisdobsza", "Kisszentmárton",
    "Kőbölkút", "Kökény", "Kölked", "Kővágószőlős", "Kővágótöttős", "Kozármisleny",
    "Lánycsók", "Lothárd", "Mágocs", "Majs", "Mánfa", "Martonfa", "Mecseknádasd",
    "Mecsekpölöske", "Mecsekrákos", "Mindszentgodisa", "Mozsgó", "Nagynyárád", "Orfű",
    "Pellérd", "Pécsudvard", "Pogány", "Romonya", "Sásd", "Somberek", "Szemely",
    "Szilvás", "Téseny", "Vajszló", "Versend", "Villány", "Vókány",
    EGYEB_OPCIO,
  ],
  "Bács-Kiskun": [
    "Kecskemét", "Baja", "Kiskunfélegyháza", "Kiskunhalas", "Kalocsa", "Kiskunmajsa",
    "Kiskőrös", "Kunszentmiklós", "Lajosmizse", "Bácsalmás", "Soltvadkert", "Tiszakécske",
    "Dunavecse", "Izsák", "Jánoshalma", "Tompa",
    "Akasztó", "Apostag", "Bácsbokod", "Bácsborsód", "Bácsszőlős", "Ballószög", "Bugac",
    "Bugacpusztaháza", "Csengőd", "Csikéria", "Dunapataj", "Dunatetétlen", "Fajsz", "Foktő",
    "Fülöpháza", "Fülöpszállás", "Gara", "Harta", "Hercegszántó", "Jakabszállás",
    "Kecel", "Kelebia", "Kisszállás", "Kunbaja", "Kunbaracs", "Kunfehértó", "Kunpeszér",
    "Lakitelek", "Madaras", "Mélykút", "Orgovány", "Pálmonostora", "Páhi", "Rém",
    "Solt", "Sükösd", "Szabadszállás", "Szalkszentmárton", "Tass", "Tataháza", "Üllés",
    EGYEB_OPCIO,
  ],
  "Békés": [
    "Békéscsaba", "Gyula", "Orosháza", "Szarvas", "Békés", "Mezőberény", "Szeghalom",
    "Gyomaendrőd", "Mezőkovácsháza", "Dévaványa", "Füzesgyarmat", "Körösladány",
    "Köröstarcsa", "Békésszentandrás", "Tótkomlós", "Vésztő", "Elek", "Kondoros", "Kétegyháza",
    "Almáskamarás", "Battonya", "Biharugra", "Bucsa", "Csabacsűd", "Csárdaszállás",
    "Csorvás", "Doboz", "Gádoros", "Geszt", "Kamut", "Kétsoprony", "Kisdombegyház",
    "Lőkösháza", "Medgyesegyháza", "Mezőgyán", "Murony", "Nagyszénás", "Örménykút",
    "Pusztaföldvár", "Szabadkígyós", "Tarhos", "Telekgerendás", "Újiráz",
    EGYEB_OPCIO,
  ],
  "Borsod-Abaúj-Zemplén": [
    "Miskolc", "Kazincbarcika", "Ózd", "Tiszaújváros", "Mezőkövesd", "Sátoraljaújhely",
    "Sárospatak", "Szerencs", "Edelény", "Sajószentpéter", "Putnok", "Szikszó",
    "Encs", "Mezőcsát", "Tokaj",
    "Aggtelek", "Alsózsolca", "Arnót", "Bodroghalom", "Boldva", "Borsodnádasd",
    "Cigánd", "Felsőzsolca", "Füzér", "Gönc", "Göncruszkà", "Hernádkak", "Hernádnémeti",
    "Hollóháza", "Igrici", "Karcsa", "Mád", "Mályi", "Múcsony", "Novajidrány",
    "Nyékládháza", "Olaszliszka", "Pálháza", "Prügy", "Ricse", "Sajókaza",
    "Sajókeresztúr", "Sajólád", "Sajóörs", "Sajószöged", "Sárazsadány",
    "Taktaharkány", "Taktaszada", "Tard", "Telkibánya", "Tiszabábolna", "Tiszadob",
    "Tiszaladány", "Tiszalúc", "Tolcsva", "Varbó",
    EGYEB_OPCIO,
  ],
  "Csongrád-Csanád": [
    "Szeged", "Hódmezővásárhely", "Szentes", "Makó", "Csongrád", "Mórahalom",
    "Kistelek", "Mindszent",
    "Algyő", "Ásotthalom", "Bordány", "Csanytelek", "Csengele", "Deszk", "Dóc",
    "Domaszék", "Fábiánsebestyén", "Felgyő", "Ferencszállás", "Földeák", "Forráskút",
    "Kübekháza", "Maroslele", "Mártély", "Nagymágocs", "Nagyér", "Nagytőke", "Óföldeák",
    "Öttömös", "Pitvaros", "Röszke", "Rúzsa", "Sándorfalva", "Szatymaz",
    "Tömörkény", "Zákányszék",
    EGYEB_OPCIO,
  ],
  "Fejér": [
    "Székesfehérvár", "Dunaújváros", "Mór", "Bicske", "Gárdony", "Sárbogárd",
    "Ercsi", "Pusztaszabolcs", "Enying", "Adony", "Lepsény", "Martonvásár",
    "Polgárdi", "Csákvár", "Seregélyes", "Velence",
    "Alsószentiván", "Baracska", "Bodajk", "Csór", "Fehérvárcsurgó", "Iváncsa",
    "Káloz", "Kisapostag", "Kisfalud", "Kulcs", "Lajoskomárom", "Lovasberény",
    "Mezőfalva", "Nadap", "Pázmánd", "Perkáta", "Pusztaegres", "Pusztavám",
    "Soponya", "Tác", "Úrhida", "Vajta", "Vál",
    EGYEB_OPCIO,
  ],
  "Győr-Moson-Sopron": [
    "Győr", "Sopron", "Mosonmagyaróvár", "Kapuvár", "Csorna", "Fertőd", "Tét",
    "Győrújfalu", "Jánossomorja",
    "Abda", "Ásványráró", "Bezenye", "Bogyoszló", "Bőny", "Börcs", "Dénesfa",
    "Dunakiliti", "Dunasziget", "Fertőboz", "Fertőrákos", "Fertőszentmiklós",
    "Győrság", "Győrszemere", "Győrújbarát", "Hédervár", "Ikrény", "Kisbajcs",
    "Kunsziget", "Lébény", "Lipót", "Lövő", "Mecsér", "Mosonszentmiklós",
    "Nagybajcs", "Nagycenk", "Nyúl", "Öttevény", "Pér", "Püski", "Rábapatona",
    "Répcelak", "Rétalap", "Röjtökmuzsaj", "Sarród", "Sopronhorpács",
    "Sopronkövesd", "Szany", "Szil", "Szilsárkány", "Töltéstava", "Veszkény",
    EGYEB_OPCIO,
  ],
  "Hajdú-Bihar": [
    "Debrecen", "Hajdúböszörmény", "Hajdúszoboszló", "Berettyóújfalu", "Hajdúhadház",
    "Hajdúnánás", "Hajdúdorog", "Balmazújváros", "Püspökladány", "Nádudvar",
    "Derecske", "Polgár", "Egyek", "Téglás", "Komádi", "Létavértes",
    "Tiszacsege", "Nyíracsád",
    "Álmosd", "Ártánd", "Bakonszeg", "Báránd", "Biharkeresztes", "Biharnagybajom",
    "Bihartorda", "Bojt", "Csökmő", "Darvas", "Ebes", "Fülöp", "Görbeháza",
    "Hajdúbagos", "Hajdúsámson", "Hajdúvid", "Kaba", "Konyár", "Körösszakál",
    "Körösszegapáti", "Mikepércs", "Monostorpályi", "Nagyhegyes", "Nyírábrány",
    "Nyíradony", "Nyírmartonfalva", "Sáp", "Szentpéterszeg", "Tépe", "Told",
    "Vámospércs", "Vekerd",
    EGYEB_OPCIO,
  ],
  "Heves": [
    "Eger", "Gyöngyös", "Hatvan", "Heves", "Füzesabony", "Gyöngyöspata",
    "Bélapátfalva", "Pétervására", "Lőrinci", "Recsk", "Sirok", "Kál", "Kisköre",
    "Abasár", "Andornaktálya", "Bodony", "Bükkszenterzsébet", "Bükkszék", "Csány",
    "Detk", "Domoszló", "Egerfarmos", "Egerszólát", "Erdőkövesd", "Erdőtelek",
    "Felsőtárkány", "Gyöngyöshalász", "Gyöngyössolymos", "Halmajugra", "Heréd",
    "Istenmezeje", "Ivád", "Kisbágyon", "Kömlő", "Maklár", "Markaz",
    "Mátraderecske", "Mátraszele", "Mátraverebély", "Mezőszemere", "Mikófalva",
    "Nagyfüged", "Nagytálya", "Párad", "Parádfürdő", "Rózsaszentmárton",
    "Szihalom", "Tarnabod", "Tarnalelesz", "Tarnaörs", "Tarnaszentmiklós",
    "Tenk", "Verpelét", "Zagyvaszántó",
    EGYEB_OPCIO,
  ],
  "Jász-Nagykun-Szolnok": [
    "Szolnok", "Jászberény", "Karcag", "Törökszentmiklós", "Mezőtúr", "Tiszafüred",
    "Tiszaföldvár", "Kunszentmárton", "Jászapáti", "Kisújszállás", "Kunhegyes",
    "Jászárokszállás", "Jászfényszaru", "Jászkisér", "Jászladány", "Kenderes",
    "Kunmadaras", "Martfű", "Abádszalók", "Túrkeve",
    "Alattyán", "Besenyszög", "Csataszög", "Csépa", "Cserkeszőlő", "Fegyvernek",
    "Kétpó", "Mesterszállás", "Nagykörű", "Örményes", "Rákóczifalva",
    "Rákócziújfalu", "Tiszabő", "Tiszaderzs", "Tiszagyenda", "Tiszainoka",
    "Tiszajenő", "Tiszakürt", "Tiszapüspöki", "Tiszaroff", "Tiszasas",
    "Tiszaszentimre", "Tiszavárkony", "Tomajmonostora", "Újszász", "Vezseny",
    "Zagyvarékas",
    EGYEB_OPCIO,
  ],
  "Komárom-Esztergom": [
    "Tatabánya", "Esztergom", "Komárom", "Tata", "Dorog", "Oroszlány", "Ács",
    "Nyergesújfalu", "Lábatlan", "Kisbér", "Süttő", "Tokod",
    "Almásfüzitő", "Annavölgy", "Bajót", "Bakonysárkány", "Dád", "Dunaalmas",
    "Dunaalmás", "Gyermely", "Héreg", "Kerékteleki", "Kesztölc", "Kömlőd",
    "Leányvár", "Mocsa", "Mogyorósbánya", "Nagyigmánd", "Naszály", "Neszmély",
    "Pilismarót", "Pusztavám", "Réde", "Szomód", "Tardos", "Tarján", "Tát",
    "Várgesztes", "Vérteskethely", "Vértestolna",
    EGYEB_OPCIO,
  ],
  "Nógrád": [
    "Salgótarján", "Balassagyarmat", "Szécsény", "Bátonyterenye", "Rétság",
    "Bercel", "Páris",
    "Alsópetény", "Bánk", "Berkenye", "Bokor", "Cserháthaláp", "Csesztve",
    "Dejtár", "Diósjenő", "Érsekvadkert", "Etes", "Herencsény", "Hollókő",
    "Hugyag", "Ipolyszög", "Ipolytarnóc", "Jobbágyi", "Karancsberény",
    "Karancslapujtő", "Karancsság", "Kozárd", "Lucfalva", "Magyargéc",
    "Mátraszőlős", "Mátraverebély", "Mihálygerge", "Nógrád", "Nógrádmegyer",
    "Nógrádmarcal", "Nógrádkövesd", "Pálfalva", "Patvarc", "Pusztaberki",
    "Rimóc", "Romhány", "Ságújfalu", "Sámsonháza", "Sóshartyán", "Szanda",
    "Szilaspogony", "Szirák", "Tar", "Terény", "Tereske", "Tolmács", "Varsány",
    EGYEB_OPCIO,
  ],
  "Pest": [
    "Érd", "Budaörs", "Vác", "Cegléd", "Gödöllő", "Dunakeszi", "Szentendre",
    "Nagykőrös", "Dabas", "Szigetszentmiklós", "Vecsés", "Dunaharaszti", "Gyál",
    "Gyömrő", "Ráckeve", "Monor", "Pilisvörösvár", "Pomáz", "Százhalombatta",
    "Nagykáta", "Lajosmizse", "Kiskunlacháza", "Budakeszi", "Fót",
    "Albertirsa", "Aszód", "Maglód",
    "Alsónémedi", "Biatorbágy", "Budajenő", "Budakalász", "Bugyi", "Csobánka",
    "Délegyháza", "Ecser", "Erdőkertes", "Göd", "Gyömrő", "Halásztelek",
    "Hernád", "Isaszeg", "Kerepes", "Kiskőrös", "Kismaros", "Kisnémedi",
    "Leányfalu", "Márianosztra", "Mogyoród", "Monorierdő", "Nagytarcsa",
    "Nyáregyháza", "Ócsai", "Páty", "Pécel", "Perbál", "Pilisborosjenő",
    "Piliscséb", "Piliscsév", "Pilisszántó", "Pilisszentiván", "Pilisszentkereszt",
    "Pilisszentlászló", "Pócsmegyer", "Sülysáp", "Szigethalom", "Szentmártonkáta",
    "Tahitótfalu", "Tinnye", "Tököl", "Törökbálint", "Tura", "Üröm",
    "Vácrátót", "Veresegyház", "Visegrád",
    EGYEB_OPCIO,
  ],
  "Somogy": [
    "Kaposvár", "Siófok", "Marcali", "Nagyatád", "Barcs", "Csurgó", "Fonyód",
    "Balatonboglár", "Balatonföldvár", "Balatonlelle", "Balatonszárszó",
    "Balatonfenyves", "Kadarkút", "Zamárdi",
    "Balatonendréd", "Balatonkeresztúr", "Balatonmáriafürdő", "Balatonszemese",
    "Balatonszentgyörgy", "Bohonye", "Csokonyavisonta", "Gamás", "Gálosfa",
    "Gyékényes", "Iharosberény", "Karád", "Kéthely", "Lengyeltóti", "Lulla",
    "Mernye", "Mezőcsokonya", "Mike", "Nágocs", "Nikla", "Öreglak",
    "Ötvöskónyi", "Porrog", "Rinyabesenyő", "Rinyaszentkirály", "Segesd",
    "Somogybabod", "Somogydöröcske", "Somogyudvarhely", "Somogyvámos",
    "Tab", "Taszár", "Vése",
    EGYEB_OPCIO,
  ],
  "Szabolcs-Szatmár-Bereg": [
    "Nyíregyháza", "Kisvárda", "Nyírbátor", "Mátészalka", "Vásárosnamény",
    "Fehérgyarmat", "Tiszavasvári", "Nagykálló", "Záhony", "Baktalórántháza",
    "Balkány", "Csenger", "Ibrány", "Kemecse", "Kotaj", "Levelek", "Mándok",
    "Máriapócs", "Nagyecsed", "Nyírmada", "Nyírtelek", "Tiszalök",
    "Ajak", "Anarcs", "Biri", "Botpalád", "Csaholc", "Csegöld", "Csengersima",
    "Demecser", "Dombrád", "Encsencs", "Eperjeske", "Fülpösdaróc", "Gemzse",
    "Gyügye", "Hodász", "Jánd", "Jánkmajtis", "Kállósemjén", "Kántorjánosi",
    "Kék", "Kisléta", "Kispalád", "Kisszekeres", "Komoró", "Lövőpetri",
    "Milota", "Nábrád", "Nagyar", "Nagydobos", "Nagygéc", "Nagyhalász",
    "Nagyhódos", "Nagysemjén", "Nyírcsaholy", "Nyírderzs", "Nyírgelse",
    "Nyírgyulaj", "Nyírlugos", "Nyírmeggyes", "Nyírparasznya", "Nyírpazony",
    "Nyírpilis", "Nyírtura", "Nyírvasvári", "Ópályi", "Ököritófülpös",
    "Panyola", "Penészlek", "Petneháza", "Piricse", "Porcsalma", "Rohod",
    "Rozsály", "Sonkád", "Szabolcs", "Szabolcsbáka", "Szatmárcseke",
    "Tiszabercel", "Tiszabezdéd", "Tiszaeszlár", "Tiszakanyár", "Tiszanagyfalu",
    EGYEB_OPCIO,
  ],
  "Tolna": [
    "Szekszárd", "Dombóvár", "Bonyhád", "Paks", "Tamási", "Bátaszék",
    "Dunaföldvár", "Simontornya", "Tolna", "Fadd",
    "Alsónyék", "Bátaapáti", "Báta", "Bogyiszló", "Decs", "Dunaszentgyörgy",
    "Fácánkert", "Felsőnána", "Gyönk", "Harc", "Hőgyész", "Iregszemcse",
    "Kéty", "Kisdorog", "Kölesd", "Lengyel", "Medina", "Mőcsény", "Mucsfa",
    "Murga", "Nagydorog", "Nagymányok", "Nagyszékely", "Őcsény", "Ozora",
    "Pálfa", "Pincehely", "Regöly", "Sárpilis", "Szálka", "Tengelic",
    "Váralja", "Závod", "Zomba",
    EGYEB_OPCIO,
  ],
  "Vas": [
    "Szombathely", "Sárvár", "Kőszeg", "Körmend", "Celldömölk", "Répcelak",
    "Csepreg", "Vasvár", "Jánosháza",
    "Balogunyom", "Boba", "Bucsu", "Bük", "Csánig", "Farkasfa", "Gencsapáti",
    "Gérce", "Győrvár", "Hegyfalu", "Hosszúpereszteg", "Ispánk", "Kemeneskápolna",
    "Kemenessömjén", "Kétvölgy", "Kisrákos", "Lukácsháza", "Magyarszecsőd",
    "Mesteri", "Molnari", "Nádasd", "Nemescsó", "Olaszfa", "Ostffyasszonyfa",
    "Pinkamindszent", "Pornóapáti", "Rábagyarmat", "Rábahídvég", "Rábakovácsi",
    "Rátót", "Rum", "Sé", "Sorkifalud", "Sorkikápolna", "Söpte", "Szemenye",
    "Szentpéterfa", "Tömörd", "Torony", "Vasszécsény", "Vat", "Velemér",
    EGYEB_OPCIO,
  ],
  "Veszprém": [
    "Veszprém", "Pápa", "Ajka", "Balatonfüred", "Tapolca", "Várpalota",
    "Balatonalmádi", "Zirc", "Sümeg", "Devecser", "Herend", "Berhida",
    "Badacsonytomaj",
    "Alsóörs", "Aszófő", "Balatoncsicsó", "Balatonederics", "Balatonfőkajár",
    "Balatongyörök", "Balatonhenye", "Balatonkenese", "Balatonrendes",
    "Balatonszepezd", "Balatonudvari", "Bakonybél", "Bakonynána", "Bakonyoszlop",
    "Csopak", "Eplény", "Fűzfőgyártelep", "Hajmáskér", "Hegymagas", "Hidegkút",
    "Kapolcs", "Kékkút", "Lovas", "Lókút", "Mindszentkálla", "Monostorapáti",
    "Mencshely", "Nemesvámos", "Nemesvita", "Örvényes", "Pécsely", "Pula",
    "Révfülöp", "Salföld", "Sáska", "Szentantalfa", "Szentbékkálla",
    "Taliándörögd", "Tihany", "Úrkút", "Vászoly",
    EGYEB_OPCIO,
  ],
  "Zala": [
    "Zalaegerszeg", "Nagykanizsa", "Keszthely", "Hévíz", "Lenti", "Zalaszentgrót",
    "Letenye", "Pacsa", "Zalaszentlőrinc",
    "Alsópáhok", "Balatonmagyaród", "Balatonszentgyörgy", "Böde", "Cserszegtomaj",
    "Dióskál", "Felsőpáhok", "Galambok", "Garabonc", "Gelse", "Gyenesdiás",
    "Kerkaszentkirály", "Kiscsehi", "Kisgörbő", "Kisrécse", "Liszó",
    "Magyarszentmiklós", "Murakeresztúr", "Nagyrécse", "Nemesrádó", "Nova",
    "Orosztony", "Ötvös", "Pölöske", "Sármellék", "Söjtör", "Szepetnek",
    "Teskánd", "Vállus", "Vindornyafok", "Zalaapáti", "Zalabér", "Zalacsány",
    "Zalacséb", "Zalaháshágy", "Zalakoppány", "Zalalövő", "Zalaszabar",
    "Zalaszentbalázs", "Zalaszentiván", "Zalaújlak", "Zalavár",
    EGYEB_OPCIO,
  ],
};
