-- Védett Karrier – Easy Language szövegfrissítés (2026-09-22)
-- Kizárólag a job_families tábla felhasználó felé megjelenő szöveges
-- mezőit (name_hu, description_hu, task_pattern_summary) egyszerűsíti.
-- A slug, a display_order, az enum/kód-mezők (core_skills_json stb.) és
-- minden egyéb adat VÁLTOZATLAN marad. Nincs séma-/oszlopváltozás.

UPDATE job_families SET name_hu = 'Irodai adminisztratív munka', description_hu = 'Rendszeres irodai feladatok. Iratokkal és adatokkal dolgozol, és egyszerű ügyeket intézel.', task_pattern_summary = 'Rendszeresen ismétlődő irodai feladatok. Általában előre tudod, mit és milyen sorrendben kell csinálnod.' WHERE slug = 'admin-strukturalt';
UPDATE job_families SET name_hu = 'Adatkezelés és adatbevitel', description_hu = 'Adatokat viszel be és ellenőrzöl számítógépes rendszerekben. Pontosan és figyelmesen kell dolgoznod.', task_pattern_summary = 'Adatokat rögzítesz és ellenőrzöl egy előre megadott formában.' WHERE slug = 'adatbevitel-adatkezeles';
UPDATE job_families SET name_hu = 'Dokumentáció és nyilvántartás', description_hu = 'Papíron és számítógépen lévő iratokat rendszerezel. Elrakod őket úgy, hogy később könnyen megtaláld.', task_pattern_summary = 'Iratokat rendezel, elraktározol, és később előkeresel.' WHERE slug = 'dokumentacio-nyilvantartas';
UPDATE job_families SET name_hu = 'Digitális háttérmunka', description_hu = 'Online feladatokat végzel számítógépen. Nem kell ügyfelekkel közvetlenül beszélned.', task_pattern_summary = 'Online rendszereket kezelsz, és adatokat dolgozol fel a háttérben.' WHERE slug = 'digitalis-hattermunka';
UPDATE job_families SET name_hu = 'Minőségellenőrzés', description_hu = 'Rendszeresen ellenőrzöl termékeket, iratokat vagy folyamatokat. Egy előre megadott szabály alapján nézed meg, hogy megfelelő-e.', task_pattern_summary = 'Ellenőrzöd, hogy egy termék vagy adat megfelelő-e. Jelzed, ha hibát találsz.' WHERE slug = 'minoseg-ellenorzes';
UPDATE job_families SET name_hu = 'Raktári és logisztikai munka', description_hu = 'Árut mozgatsz, tárolsz és megszámolsz egy raktárban vagy hasonló helyen.', task_pattern_summary = 'Árut mozgatsz kézzel, és nyilvántartod, mennyi van belőle.' WHERE slug = 'keszlet-logisztika';
UPDATE job_families SET name_hu = 'Gépek karbantartása', description_hu = 'Gépeket és eszközöket kezelsz és karbantartasz. Jelzed, ha valami elromlik.', task_pattern_summary = 'Gépeket kezelsz, ellenőrzöl, és egyszerű karbantartást végzel rajtuk.' WHERE slug = 'technikai-karbantartas';
UPDATE job_families SET name_hu = 'Kutatás és információgyűjtés', description_hu = 'Adatokat és információkat gyűjtesz össze, és rendszerezed őket.', task_pattern_summary = 'Információt keresel, rendszerezel, és röviden összefoglalod.' WHERE slug = 'kutatas-informaciofeldolgozas';
UPDATE job_families SET name_hu = 'Kreatív digitális munka', description_hu = 'Képeket, szövegeket vagy más digitális tartalmakat készítesz és szerkesztesz.', task_pattern_summary = 'Digitális tartalmat készítesz és szerkesztesz egyszerű programokkal.' WHERE slug = 'kreativ-digitalis';
UPDATE job_families SET name_hu = 'Kézi, precíz munka', description_hu = 'Ügyes kézzel dolgozol: összeszerelsz, válogatsz, vagy ellenőrzöl apró tárgyakat.', task_pattern_summary = 'Pontos kézi munkát végzel: összerakod vagy megvizsgálod az apró alkatrészeket.' WHERE slug = 'kezzel-preciz';
UPDATE job_families SET name_hu = 'Kertészeti munka', description_hu = 'Növényeket gondozol, kertészkedsz, vagy zöldterületeket ápolsz.', task_pattern_summary = 'Növényeket öntözöl, gondozol, és zöldterületeket rendben tartasz.' WHERE slug = 'novenyek-kornyezet';
UPDATE job_families SET name_hu = 'Élelmiszer-előkészítés', description_hu = 'Ételt készítesz elő, csomagolsz, vagy egyszerű módon elkészítesz. Fontos a tisztaság.', task_pattern_summary = 'Élelmiszerrel dolgozol: előkészíted és csomagolod, a tisztasági szabályok szerint.' WHERE slug = 'elelmiszer-elokeszites';
UPDATE job_families SET name_hu = 'Segítségnyújtás embereknek', description_hu = 'Embereknek segítesz a mindennapi dolgaikban. Ez nem terápia, hanem gyakorlati segítség.', task_pattern_summary = 'Segítesz másoknak elvégezni a mindennapi feladataikat.' WHERE slug = 'gondoskodas-tamogatas';
UPDATE job_families SET name_hu = 'Takarítás és rendrakás', description_hu = 'Épületeket, területeket vagy eszközöket takarítasz és rendben tartasz.', task_pattern_summary = 'Rendszeresen takarítasz egy előre megadott rend szerint.' WHERE slug = 'tisztasag-rendezettség';
UPDATE job_families SET name_hu = 'Szállítás és kézbesítés', description_hu = 'Csomagokat vagy iratokat szállítasz egy megadott útvonalon.', task_pattern_summary = 'Csomagokat szállítasz és kézbesítesz egy megadott útvonalon.' WHERE slug = 'szallitas-fuvarozas';
UPDATE job_families SET name_hu = 'Ügyfelek tájékoztatása', description_hu = 'Ügyfeleket fogadsz, és válaszolsz az egyszerű kérdéseikre.', task_pattern_summary = 'Ügyfeleket segítesz személyesen vagy telefonon.' WHERE slug = 'ugyfel-informacios';
UPDATE job_families SET name_hu = 'Pénztári és pénzügyi munka', description_hu = 'Pénzt kezelsz, számlákat állítasz ki, és egyszerű pénzügyi nyilvántartást vezetsz.', task_pattern_summary = 'Rögzíted a pénzmozgásokat, és kezeled a pénztárt.' WHERE slug = 'keszpenz-penzugyi-admin';
UPDATE job_families SET name_hu = 'Szövegek szerkesztése', description_hu = 'Szövegeket írsz, szerkesztesz vagy formázol.', task_pattern_summary = 'Szövegeket javítasz, rendezel és formázol.' WHERE slug = 'szoveges-tartalom';
UPDATE job_families SET name_hu = 'Vizuális tartalmak készítése', description_hu = 'Képeket, grafikákat vagy prezentációkat készítesz és szerkesztesz.', task_pattern_summary = 'Képeket és bemutatókat szerkesztesz kész sablonok alapján.' WHERE slug = 'vizualis-designtamogatas';
UPDATE job_families SET name_hu = 'Oktatás támogatása', description_hu = 'Segítesz egy oktatás vagy képzés megszervezésében és lebonyolításában.', task_pattern_summary = 'Előkészíted és rendben tartod egy képzés anyagait és adatait.' WHERE slug = 'oktatasi-tamogatas';
UPDATE job_families SET name_hu = 'Megfigyelés', description_hu = 'Figyelsz egy területet vagy folyamatot, és jelzed, ha valami nem stimmel.', task_pattern_summary = 'Rendszeresen figyelsz valamit, és észreveszed, ha eltérés van.' WHERE slug = 'megfigyeles-monitorozas';
UPDATE job_families SET name_hu = 'Csomagolás és válogatás', description_hu = 'Termékeket csomagolsz és válogatsz kézzel.', task_pattern_summary = 'Ugyanazt a csomagolási vagy válogatási munkát ismétled sokszor.' WHERE slug = 'kezi-csomagolas-valogatás';
UPDATE job_families SET name_hu = 'Kültéri munka', description_hu = 'A szabadban dolgozol: mérsz, felmérsz, vagy karbantartasz valamit.', task_pattern_summary = 'Rendszeresen a szabadban végzett munkafeladatok.' WHERE slug = 'terep-kulteri-munka';
UPDATE job_families SET name_hu = 'Online ügyintézés', description_hu = 'Ügyeket intézel online felületeken: kérvényeket és nyomtatványokat töltesz ki.', task_pattern_summary = 'Ügyeket intézel számítógépes rendszerekben, online.' WHERE slug = 'digitalis-ugyintezes';
UPDATE job_families SET name_hu = 'Közösségi programok segítése', description_hu = 'Segítesz megszervezni közösségi programokat és csoportos tevékenységeket.', task_pattern_summary = 'Előkészíted és rendben tartod egy közösségi program helyszínét és anyagait.' WHERE slug = 'szociometriai-kozossegi';
